//
//  SettingsKeys.swift
//  MacBox
//
//  Created by Strongbox on 07/03/2023.
//  Copyright © 2023 Mark McGuill. All rights reserved.
//

import Cocoa

@objc
enum SettingsKeys : Int {
    case databases
    case pro
    case endFreeTrialDate
    case autoLockTimeout
    case autoLockIfInBackgroundTimeoutSeconds
    case alwaysShowPassword
    case autoFillNewRecordSettings
    case autoSave
    case clearClipboardEnabled
    case clearClipboardAfterSeconds
    case floatOnTop
    case passwordGenerationConfig
    case trayPasswordGenerationConfig
    case autoPromptForTouchIdOnActivate
    case showSystemTrayIcon
    case favIconDownloadOptions
    case showPasswordImmediatelyInOutline
    case hideKeyFileNameOnLockScreen
    case doNotRememberKeyFile
    case allowEmptyOrNoPasswordEntry
    case colorizePasswords
    case colorizeUseColorBlindPalette
    case clipboardHandoff
    case showDatabasesManagerOnCloseAllWindows
    case showAutoFillTotpCopiedMessage
    case autoLaunchSingleDatabase
    case hideDockIconOnAllMinimized
    case closeManagerOnLaunch
    case makeLocalRollingBackups
    case miniaturizeOnCopy
    case quickRevealWithOptionKey
    case markdownNotes
    case showPasswordGenInTray
    case nextGenUI
    case addOtpAuthUrl
    case addLegacySupplementaryTotpCustomFields
    case quitOnAllWindowsClosed
    case lastPromptedToUseNextGenUI
    case showCopyFieldButton
    case lockEvenIfEditing
    case screenCaptureBlocked
    case lastEntitlementCheckAttempt
    case numberOfEntitlementCheckFails
    case appHasBeenDowngradedToFreeEdition
    case hasPromptedThatAppHasBeenDowngradedToFreeEdition
    case hasPromptedThatFreeTrialWillEndSoon
    case hasShownFirstRunWelcome
    case freeTrialNudgeCount
    case lastFreeTrialNudge
    case installDate
    case launchCountKey
    case useIsolatedDropbox
    case useParentGroupIconOnCreate
    case stripUnusedIconsOnSave
    case runBrowserAutoFillProxyServer
    case quitTerminatesProcessEvenInSystemTrayMode
    case lockDatabaseOnWindowClose
    case lockDatabasesOnScreenLock
    case showDatabasesManagerOnAppLaunch
    case hasAskedAboutDatabaseOpenInBackground
    case concealClipboardFromMonitors
    case autoCommitScannedTotp
    case hideOnCopy
    case hasPromptedForThirdPartyAutoFill

    var keyString : String {
        switch self {
        case .databases:
            return "databases"
        case .pro:
            return "fullVersion"
        case .endFreeTrialDate:
            return "endFreeTrialDate"
        case .autoLockTimeout:
            return "autoLockTimeout"
        case .autoLockIfInBackgroundTimeoutSeconds:
            return "autoLockIfInBackgroundTimeoutSeconds"
        case .alwaysShowPassword:
            return "alwaysShowPassword"
        case .autoFillNewRecordSettings:
            return "autoFillNewRecordSettings"
        case .autoSave:
            return "autoSave"
        case .clearClipboardEnabled:
            return "clearClipboardEnabled"
        case .clearClipboardAfterSeconds:
            return "clearClipboardAfterSeconds"
        case .floatOnTop:
            return "floatOnTop"
        case .passwordGenerationConfig:
            return "passwordGenerationConfig"
        case .trayPasswordGenerationConfig:
            return "trayPasswordGenerationConfig"
        case .autoPromptForTouchIdOnActivate:
            return "autoPromptForTouchIdOnActivate"
        case .showSystemTrayIcon:
            return "showSystemTrayIcon"
        case .favIconDownloadOptions:
            return "favIconDownloadOptions"
        case .showPasswordImmediatelyInOutline:
            return "showPasswordImmediatelyInOutline"
        case .hideKeyFileNameOnLockScreen:
            return "hideKeyFileNameOnLockScreen"
        case .doNotRememberKeyFile:
            return "doNotRememberKeyFile"
        case .allowEmptyOrNoPasswordEntry:
            return "allowEmptyOrNoPasswordEntry"
        case .colorizePasswords:
            return "colorizePasswords"
        case .colorizeUseColorBlindPalette:
            return "colorizeUseColorBlindPalette"
        case .clipboardHandoff:
            return "clipboardHandoff"
        case .showDatabasesManagerOnCloseAllWindows:
            return "showDatabasesManagerOnCloseAllWindows"
        case .showAutoFillTotpCopiedMessage:
            return "showAutoFillTotpCopiedMessage"
        case .autoLaunchSingleDatabase:
            return "autoLaunchSingleDatabase"
        case .hideDockIconOnAllMinimized:
            return "hideDockIconOnAllMinimized"
        case .closeManagerOnLaunch:
            return "closeManagerOnLaunch"
        case .makeLocalRollingBackups:
            return "makeLocalRollingBackups"
        case .miniaturizeOnCopy:
            return "miniaturizeOnCopy"
        case .quickRevealWithOptionKey:
            return "quickRevealWithOptionKey"
        case .markdownNotes:
            return "markdownNotes"
        case .showPasswordGenInTray:
            return "showPasswordGenInTray"
        case .nextGenUI:
            return "nextGenUI-Production-17-Mar-2022"
        case .addOtpAuthUrl:
            return "addOtpAuthUrl"
        case .addLegacySupplementaryTotpCustomFields:
            return "addLegacySupplementaryTotpCustomFields"
        case .quitOnAllWindowsClosed:
            return "quitOnAllWindowsClosed"
        case .lastPromptedToUseNextGenUI:
            return "lastPromptedToUseNextGenUI"
        case .showCopyFieldButton:
            return "showCopyFieldButton"
        case .lockEvenIfEditing:
            return "lockEvenIfEditing"
        case .screenCaptureBlocked:
            return "screenCaptureBlocked"
        case .lastEntitlementCheckAttempt:
            return "lastEntitlementCheckAttempt"
        case .numberOfEntitlementCheckFails:
            return "numberOfEntitlementCheckFails-reset-all-27-dec-2022"
        case .appHasBeenDowngradedToFreeEdition:
            return "appHasBeenDowngradedToFreeEdition"
        case .hasPromptedThatAppHasBeenDowngradedToFreeEdition:
            return "hasPromptedThatAppHasBeenDowngradedToFreeEdition"
        case .hasPromptedThatFreeTrialWillEndSoon:
            return "hasPromptedThatFreeTrialWillEndSoon"
        case .hasShownFirstRunWelcome:
            return "hasShownFirstRunWelcome"
        case .freeTrialNudgeCount:
            return "freeTrialNudgeCount"
        case .lastFreeTrialNudge:
            return "lastFreeTrialNudge"
        case .installDate:
            return "installDate"
        case .launchCountKey:
            return "launchCountKey"
        case .useIsolatedDropbox:
            return "useIsolatedDropbox"
        case .useParentGroupIconOnCreate:
            return "useParentGroupIconOnCreate"
        case .stripUnusedIconsOnSave:
            return "stripUnusedIconsOnSave"
        case .runBrowserAutoFillProxyServer:
            return "runBrowserAutoFillProxyServer-Prod-22-Oct-2022"
        case .quitTerminatesProcessEvenInSystemTrayMode:
            return "quitTerminatesProcessEvenInSystemTrayMode"
        case .lockDatabaseOnWindowClose:
            return "lockDatabaseOnWindowClose"
        case .lockDatabasesOnScreenLock:
            return "lockDatabasesOnScreenLock"
        case .showDatabasesManagerOnAppLaunch:
            return "showDatabasesManagerOnAppLaunch"
        case .hasAskedAboutDatabaseOpenInBackground:
            return "hasAskedAboutDatabaseOpenInBackground"
        case .concealClipboardFromMonitors:
            return "concealClipboardFromMonitors-DefaultON-27-Dec-2022"
        case .autoCommitScannedTotp:
            return "autoCommitScannedTotp"
        case .hideOnCopy:
            return "hideOnCopy"
        case .hasPromptedForThirdPartyAutoFill:
            return "hasPromptedForThirdPartyAutoFill"
        }
    }
}
